#!/usr/bin/env ksh
PARTITION=$(dirname $(dirname $0))
TESTGEN="$PARTITION/testgen/"
BASE="$(basename "$0")"
function usage {
    echo "Usage: $BASE N"
}

case $1 in
    +([0-9])) N=$1 ;;
    *) usage; exit 1 ;;
esac

gen=$TESTGEN/dist/build/testgen/testgen
solution="$(cat $SERVER105/www/solutions/scheme.lists+trees)"
mktests=$($gen --test flatten --size 15 --suitesize $N | awk '{ printf "(mktest %s)\n", $0 }')
scm=$(cat <<EOF
$solution
(define mktest (lops)
  (list4 'check-expect
         (list3 'flatten '# lops)
         '# (flatten lops)))
$mktests
EOF
)

echo "$scm" | uscheme -q | sed "s/# /'/g" | grep 'check-expect'
