#!/usr/bin/env ksh -e
prog=$(basename $0)
function usage {
    echo "Usage: $prog unit outcomes"
    exit 1
}

[[ $# -eq 2 ]] || usage

PARTITION=$(dirname $(dirname $0))
RANK=$(ls $PARTITION/partition-fest/rank.*)

unit="$1"
outcomes="$2"

grades=$(mktemp -t "grades-$unit-XXXXX")
utln-of-outcomes -u "$unit" < "$outcomes" > "$grades"

partitions=$(mktemp -t "partitioned-$unit-XXXXX")
partition-outcomes -u "$unit" < "$outcomes" > "$partitions"

sml @SMLload=$RANK -g "$grades" "$partitions"

