SOURCES=`echo *.sml *.cm */*.sml */*.sig`

all:V: njbin

# compile with mlton
swiss-army-knife: $SOURCES compile.mlb
	mlton -verbose 1 -output $target compile.mlb


nj:V: # compile with sml/nj
	echo 'CM.make "compile.cm";' | sml


njbin:V:
	sml <<'EOF'
    CM.make "$smlnj-tdp/back-trace.cm";
	CM.make "compile.cm";
	SMLofNJ.exportFn ("rank", fn x => BackTrace.monitor (fn () => CommandLine.run x));
	EOF



